"""add columns to specify current study year

Revision ID: f519333ddcef
Revises: 18e60c8dff57
Create Date: 2025-10-04 15:06:15.514454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f519333ddcef'
down_revision = '18e60c8dff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_years', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
    op.execute("COMMIT")
