"""add general schedules table

Revision ID: 10d1b9cd866e
Revises: 7b107756b34b
Create Date: 2025-09-20 15:53:55.654118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10d1b9cd866e'
down_revision = '7b107756b34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FIRST', 'SECOND', name='semesterenum').create(op.get_bind())
    op.create_table('general_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', postgresql.ENUM('FIRST', 'SECOND', name='semesterenum', create_type=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mass_content', sa.String(length=100), nullable=False),
    sa.Column('is_mass_attendance_check', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lesson_content', sa.String(length=100), nullable=False),
    sa.Column('is_lesson_attendance_check', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('study_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_year_id'], ['study_years.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_schedules')
    sa.Enum('FIRST', 'SECOND', name='semesterenum').drop(op.get_bind())
    # ### end Alembic commands ###
    op.execute("COMMIT")
