"""add leave status

Revision ID: 20a08e24d9eb
Revises: d5f6da589505
Create Date: 2025-10-18 10:41:58.296936

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '20a08e24d9eb'
down_revision = 'd5f6da589505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='attendancestatusenum',
        new_values=['PRESENT', 'ABSENT', 'LEAVE'],
        affected_columns=[TableReference(table_schema='public', table_name='student_attendances', column_name='status', existing_server_default="'ABSENT'::attendancestatusenum")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='attendancestatusenum',
        new_values=['PRESENT', 'ABSENT'],
        affected_columns=[TableReference(table_schema='public', table_name='student_attendances', column_name='status', existing_server_default="'ABSENT'::attendancestatusenum")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
