"""add catechists table

Revision ID: 67d435895776
Revises: 
Create Date: 2025-09-20 14:06:59.885975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '67d435895776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MALE_CATECHIST', 'FEMALE_CATECHIST', 'NUN', 'MONK', 'FATHER', name='titleenum').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', name='genderenum').create(op.get_bind())
    op.create_table('catechists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', postgresql.ENUM('MALE_CATECHIST', 'FEMALE_CATECHIST', 'NUN', 'MONK', 'FATHER', name='titleenum', create_type=False), nullable=False),
    sa.Column('saint_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='genderenum', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catechists')
    sa.Enum('MALE_CATECHIST', 'FEMALE_CATECHIST', 'NUN', 'MONK', 'FATHER', name='titleenum').drop(op.get_bind())
    sa.Enum('MALE', 'FEMALE', name='genderenum').drop(op.get_bind())
    # ### end Alembic commands ###
    op.execute("COMMIT")
