"""add unit students table

Revision ID: b43f50441c14
Revises: a5033e9b1a6e
Create Date: 2025-09-20 15:09:56.527268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43f50441c14'
down_revision = 'a5033e9b1a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('student_id', 'unit_id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_students')
    # ### end Alembic commands ###
    op.execute("COMMIT")

