"""add study year table

Revision ID: a2baf67dc9e8
Revises: c40ba30c0a2c
Create Date: 2025-09-20 14:24:21.911378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2baf67dc9e8'
down_revision = 'c40ba30c0a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('main_subject', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_years_code'), ['code'], unique=True)

    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_years_code'))

    op.drop_table('study_years')
    # ### end Alembic commands ###
    op.execute("COMMIT")