"""add students table

Revision ID: a5033e9b1a6e
Revises: 8b8a2d5d810b
Create Date: 2025-09-20 14:38:43.152726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a5033e9b1a6e'
down_revision = '8b8a2d5d810b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('saint_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='genderenum', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_code'), ['code'], unique=True)

    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_code'))

    op.drop_table('students')
    # ### end Alembic commands ###
    op.execute("COMMIT")
