"""add grade schedules table

Revision ID: 3c95945196e9
Revises: 10d1b9cd866e
Create Date: 2025-09-20 15:59:10.824532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c95945196e9'
down_revision = '10d1b9cd866e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', postgresql.ENUM('FIRST', 'SECOND', name='semesterenum', create_type=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mass_content', sa.String(length=100), nullable=False),
    sa.Column('is_mass_attendance_check', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lesson_content', sa.String(length=100), nullable=False),
    sa.Column('is_lesson_attendance_check', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('general_schedule_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_schedule_id'], ['general_schedules.id'], onupdate='set null', ondelete='set null'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_schedules')
    # ### end Alembic commands ###
    op.execute("COMMIT")
