"""add student attendance check

Revision ID: b14df82b8d16
Revises: 3c95945196e9
Create Date: 2025-09-20 16:22:00.787406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b14df82b8d16'
down_revision = '3c95945196e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRESENT', 'ABSENT', name='attendancestatusenum').create(op.get_bind())
    op.create_table('student_attendances',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('grade_schedule_id', sa.Integer(), nullable=False),
    sa.Column('mass_status', postgresql.ENUM('PRESENT', 'ABSENT', name='attendancestatusenum', create_type=False), server_default='ABSENT', nullable=False),
    sa.Column('is_mass_absence_notified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('lesson_status', postgresql.ENUM('PRESENT', 'ABSENT', name='attendancestatusenum', create_type=False), server_default='ABSENT', nullable=False),
    sa.Column('is_lesson_absence_notified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mass_absence_reason', sa.String(length=100), nullable=True),
    sa.Column('lesson_absence_reason', sa.String(length=100), nullable=True),
    sa.Column('catechist_id', sa.UUID(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['grade_schedule_id'], ['grade_schedules.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('student_id', 'grade_schedule_id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendances')
    sa.Enum('PRESENT', 'ABSENT', name='attendancestatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
    op.execute("COMMIT")

