"""add grades table

Revision ID: bde237b43775
Revises: a2baf67dc9e8
Create Date: 2025-09-20 14:30:40.378289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde237b43775'
down_revision = 'a2baf67dc9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head_catechist_id', sa.UUID(), nullable=True),
    sa.Column('head_assistant_catechist_id', sa.UUID(), nullable=True),
    sa.Column('accountant_catechist_id', sa.UUID(), nullable=True),
    sa.Column('study_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountant_catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['head_assistant_catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['head_catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['study_year_id'], ['study_years.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_code'), ['code'], unique=True)

    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_code'))

    op.drop_table('grades')
    # ### end Alembic commands ###
    op.execute("COMMIT")