"""add exam score table

Revision ID: 6b6f5ae66867
Revises: 89b534926123
Create Date: 2025-11-08 14:43:42.880181

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b6f5ae66867"
down_revision = "89b534926123"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exams_scores",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("student_id", "exam_id"),
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exams_scores")
    # ### end Alembic commands ###
    op.execute("COMMIT")
