"""add user accounts table

Revision ID: c40ba30c0a2c
Revises: 67d435895776
Create Date: 2025-09-20 14:14:08.902263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40ba30c0a2c'
down_revision = '67d435895776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('catechist_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_accounts_login_id'), ['login_id'], unique=True)

    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_accounts_login_id'))

    op.drop_table('user_accounts')
    # ### end Alembic commands ###
    op.execute("COMMIT")

