"""add unit catechists table

Revision ID: 7b107756b34b
Revises: b43f50441c14
Create Date: 2025-09-20 15:42:26.681671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b107756b34b'
down_revision = 'b43f50441c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_catechists',
    sa.Column('catechist_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('catechist_id', 'unit_id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_catechists')
    # ### end Alembic commands ###
    op.execute("COMMIT")
