"""add student attendance table

Revision ID: 18e60c8dff57
Revises: 3c95945196e9
Create Date: 2025-09-27 21:28:35.641535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18e60c8dff57'
down_revision = '3c95945196e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRESENT', 'ABSENT', name='attendancestatusenum').create(op.get_bind())
    sa.Enum('LESSON', 'MASS', name='attendancetypeenum').create(op.get_bind())
    op.create_table('student_attendances',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('grade_schedule_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('LESSON', 'MASS', name='attendancetypeenum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', name='attendancestatusenum', create_type=False), server_default='ABSENT', nullable=False),
    sa.Column('is_notified_absence', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('catechist_id', sa.UUID(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['grade_schedule_id'], ['grade_schedules.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('student_id', 'grade_schedule_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendances')
    sa.Enum('LESSON', 'MASS', name='attendancetypeenum').drop(op.get_bind())
    sa.Enum('PRESENT', 'ABSENT', name='attendancestatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
