"""add student parents info and parents info and contact info

Revision ID: 26b36acc5cf2
Revises: 301014c552ef
Create Date: 2026-02-21 22:37:43.091910

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "26b36acc5cf2"
down_revision = "301014c552ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "EMAIL", "PHONE", "ZALO", "FACEBOOK", "OTHER", name="contactinfotypeenum"
    ).create(op.get_bind())
    sa.Enum(
        "FATHER",
        "MOTHER",
        "GRANDFATHER",
        "GRANDMOTHER",
        "BROTHER",
        "SISTER",
        "AUNT",
        "UNCLE",
        "OTHER",
        name="contactrelationtypeenum",
    ).create(op.get_bind())
    op.create_table(
        "personal_contact_infos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=True),
        sa.Column("catechist_id", sa.UUID(), nullable=True),
        sa.Column(
            "relationship",
            postgresql.ENUM(
                "FATHER",
                "MOTHER",
                "GRANDFATHER",
                "GRANDMOTHER",
                "BROTHER",
                "SISTER",
                "AUNT",
                "UNCLE",
                "OTHER",
                name="contactrelationtypeenum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "type",
            postgresql.ENUM(
                "EMAIL",
                "PHONE",
                "ZALO",
                "FACEBOOK",
                "OTHER",
                name="contactinfotypeenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("info", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["catechist_id"], ["catechists.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("address_city", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("address_ward", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("address_quarter", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("address_street", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("address_house_no", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "is_old_address", sa.Boolean(), server_default="true", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("old_address_city", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("old_address_district", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("old_address_ward", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("old_address_quarter", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("old_address_street", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("old_address_house_no", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("father_saint_name", sa.String(length=30), nullable=True)
        )
        batch_op.add_column(
            sa.Column("father_full_name", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("father_job", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("mother_saint_name", sa.String(length=30), nullable=True)
        )
        batch_op.add_column(
            sa.Column("mother_full_name", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("mother_job", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_column("mother_job")
        batch_op.drop_column("mother_full_name")
        batch_op.drop_column("mother_saint_name")
        batch_op.drop_column("father_job")
        batch_op.drop_column("father_full_name")
        batch_op.drop_column("father_saint_name")
        batch_op.drop_column("old_address_house_no")
        batch_op.drop_column("old_address_street")
        batch_op.drop_column("old_address_quarter")
        batch_op.drop_column("old_address_ward")
        batch_op.drop_column("old_address_district")
        batch_op.drop_column("old_address_city")
        batch_op.drop_column("is_old_address")
        batch_op.drop_column("address_house_no")
        batch_op.drop_column("address_street")
        batch_op.drop_column("address_quarter")
        batch_op.drop_column("address_ward")
        batch_op.drop_column("address_city")

    op.drop_table("personal_contact_infos")
    sa.Enum(
        "FATHER",
        "MOTHER",
        "GRANDFATHER",
        "GRANDMOTHER",
        "BROTHER",
        "SISTER",
        "AUNT",
        "UNCLE",
        "OTHER",
        name="contactrelationtypeenum",
    ).drop(op.get_bind())
    sa.Enum(
        "EMAIL", "PHONE", "ZALO", "FACEBOOK", "OTHER", name="contactinfotypeenum"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
    op.execute("COMMIT")
